module.exports = {
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    MONGO_DB_LIVE_URI: process.env.MONGO_DB_LIVE_URI,
    MONGO_DB_DEV_URI: process.env.MONGO_DB_DEV_URI,
    COOKIE_KEY: process.env.COOKIE_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
};